version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "mytravel"
      POSTGRES_PASSWORD: "mytravel_pass"
      POSTGRES_DB: "mytravel_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U mytravel -d mytravel_db"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: